# ekf.yaml
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    map_frame:       map
    odom_frame:      odom        # debe existir aunque no lo uses activamente
    base_link_frame: base_link
    world_frame:     odom         # publica map → base_link

    reset_on_time_jump: true
    transform_timeout: 0.1
    publish_tf: true
    use_sim_time: true

    # ── odom0: velocidades de vel_body ────────────────────────
    odom0: /odom
    odom0_config:
      # Usamos SOLO twist (velocidades), NO pose absoluta
      #  x      y      z    roll  pitch   yaw
      - [false, false, false, false, false, false,
      #  vx     vy     vz   vroll vpitch  vyaw
         true,  true,  true, false, false, true,
      #  ax     ay     az
         false, false, false]
    odom0_differential: false  # ya tenemos velocidad directa, no diferencial

    # ── imu0: acc (con gravedad) + gyro ───────────────────────
    imu0: /imu/data_raw
    imu0_config:
      - [false, false, false,
         false, false, false,
         false, false, false,
         true,  true,  true,   # gyro → velocidades angulares
         true,  true,  true]  # acc  → aceleraciones lineales (sin Z en 2D)
    imu0_remove_gravitational_acceleration: true  # ← CRÍTICO: usamos 'acc' crudo
    imu0_differential: false